In [46]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import svm
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
from imblearn.over_sampling import SMOTE 
from sklearn.metrics import confusion_matrix

In [47]:
#Read the data into dataframe
car_df = pd.read_csv('newCardata.csv')
car_features = pd.read_csv('finalDataPreprocess.csv')

#encode the label as 1's or 0's
label_Number = LabelEncoder()
car_df['FraudFound'] = label_Number.fit_transform(car_df['FraudFound'].astype('str'))
car_label = car_df['FraudFound']
print(car_features.shape)

(15419, 97)


In [48]:
#find the all the fradulent claims in the dataset
indexOFfraudulent= []
columnfeatures= list(car_features.columns.values)
fraudulentClaims= pd.DataFrame(columns=columnfeatures)
j= 0
for i in range(car_label.shape[0]):
    if car_label[i]==1:
        fraudulentClaims.loc[j]= car_features.loc[i]
        j += 1
print(fraudulentClaims.shape)
        

(923, 97)


In [49]:
#split the data into train and test
X_train,X_test,y_train,y_test = train_test_split(car_features,car_label,random_state=3,test_size=0.25)
print(X_train.shape,X_test.shape)
X_test[:1]
print(type(X_test))

(11564, 97) (3855, 97)
<class 'pandas.core.frame.DataFrame'>


In [50]:
#model object
model = svm.SVC(kernel='linear')

In [51]:
#train the model
model.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [52]:
print('SVM classifier:')
predicted = model.predict(X_test)
print(type(predicted),predicted.shape,predicted)
print('Accuracy is ',round(accuracy_score(y_test,model.predict(X_test)) * 100,2))


SVM classifier:
<class 'numpy.ndarray'> (3855,) [0 0 0 ..., 0 0 0]
Accuracy is  93.59


In [53]:
#converting pandas.core.series.Series to numpy.ndarray
ytest = pd.Series(y_test).values
print(ytest.shape)

(3855,)


In [54]:
# calculating specifity and sensitivity
# 0  := Negative
# 1 := Positive
cm = confusion_matrix(y_test,predicted)
print("Confusion Matrix:\n",cm)
TN, FP, FN, TP = cm.ravel()

Confusion Matrix:
 [[3608    1]
 [ 246    0]]


In [55]:
TN, FP, FN, TP = cm.ravel()
print("TN:",TN)
print("FP:",FP)
print("FN:",FN)
print("TP:",TP)

print("Accuracy:",(TP+TN)/(TP+FP+FN+TN)*100)
print("Sensitivity:",TP/(TP+FN)*100)
print("Specificity:",TN/(TN+FP)*100)

TN: 3608
FP: 1
FN: 246
TP: 0
Accuracy: 93.5927367056
Sensitivity: 0.0
Specificity: 99.9722914935


In [56]:
#with SMOTE
sm = SMOTE()
features,labels = sm.fit_sample(car_features,car_label)
print(features.shape,labels.shape)
X_train,X_test,y_train,y_test = train_test_split(features,labels,random_state=3,test_size=0.25)
print(X_train.shape,X_test.shape)

(28992, 97) (28992,)
(21744, 97) (7248, 97)


In [57]:
#model object
model = svm.SVC(kernel='linear')
model.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [58]:
print('Random forest classifier:')
predicted = model.predict(X_test)
print(type(predicted),predicted.shape,predicted)
print('Accuracy is ',round(accuracy_score(y_test,model.predict(X_test)) * 100,2))

Random forest classifier:
<class 'numpy.ndarray'> (7248,) [0 1 1 ..., 0 1 1]
Accuracy is  77.33


In [59]:
# calculating specifity and sensitivity
# 0  := Negative
# 1 := Positive
cm = confusion_matrix(y_test,predicted)
print("Confusion Matrix:\n",cm)

TN, FP, FN, TP = cm.ravel()
print("TN:",TN)
print("FP:",FP)
print("FN:",FN)
print("TP:",TP)

print("Accuracy:",(TP+TN)/(TP+FP+FN+TN)*100)
print("Sensitivity:",TP/(TP+FN)*100)
print("Specificity:",TN/(TN+FP)*100)

Confusion Matrix:
 [[2187 1436]
 [ 207 3418]]
TN: 2187
FP: 1436
FN: 207
TP: 3418
Accuracy: 77.3316777042
Sensitivity: 94.2896551724
Specificity: 60.3643389456


In [16]:
#with non-linear kernel 
#model object
model = svm.SVC(C=2.0,kernel='rbf')
model.fit(X_train,y_train)

/usr/local/anaconda3/lib/python3.5/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=2.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [17]:
print('Random forest classifier:')
predicted = model.predict(X_test)
print(type(predicted),predicted.shape,predicted)
print('Accuracy is ',round(accuracy_score(y_test,model.predict(X_test)) * 100,2))
cm = confusion_matrix(y_test,predicted)
print("Confusion Matrix:\n",cm)

TN, FP, FN, TP = cm.ravel()
print("TN:",TN)
print("FP:",FP)
print("FN:",FN)
print("TP:",TP)

print("Accuracy:",(TP+TN)/(TP+FP+FN+TN)*100)
print("Sensitivity:",TP/(TP+FN)*100)
print("Specificity:",TN/(TN+FP)*100)

Random forest classifier:
<class 'numpy.ndarray'> (7248,) [1 1 1 ..., 0 1 1]
Accuracy is  79.9
Confusion Matrix:
 [[2286 1337]
 [ 120 3505]]
TN: 2286
FP: 1337
FN: 120
TP: 3505
Accuracy: 79.8979028698
Sensitivity: 96.6896551724
Specificity: 63.0968810378


In [18]:
#with polynomial kernel
model = svm.SVC(C=2,kernel='poly',degree=2,gamma='scale',coef0=0.53,tol=0.0001,decision_function_shape='ovo')
model.fit(X_train,y_train)

SVC(C=2, cache_size=200, class_weight=None, coef0=0.53,
  decision_function_shape='ovo', degree=2, gamma='scale', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.0001, verbose=False)

In [20]:
print('SVM classifier:')
predicted = model.predict(X_test)
print(type(predicted),predicted.shape,predicted)
print('Accuracy is ',round(accuracy_score(y_test,model.predict(X_test)) * 100,2))
cm = confusion_matrix(y_test,predicted)
print("Confusion Matrix:\n",cm)

TN, FP, FN, TP = cm.ravel()
print("TN:",TN)
print("FP:",FP)
print("FN:",FN)
print("TP:",TP)

print("Accuracy:",(TP+TN)/(TP+FP+FN+TN)*100)
print("Sensitivity:",TP/(TP+FN)*100)
print("Specificity:",TN/(TN+FP)*100)

Random forest classifier:
<class 'numpy.ndarray'> (7248,) [1 1 1 ..., 0 1 1]
Accuracy is  78.81
Confusion Matrix:
 [[2230 1393]
 [ 143 3482]]
TN: 2230
FP: 1393
FN: 143
TP: 3482
Accuracy: 78.8079470199
Sensitivity: 96.0551724138
Specificity: 61.5512006624


In [21]:
from numpy import linalg as LA
print(car_features.shape)
print(X_test.shape)
data= X_test[0]
data1= X_test[0]
ed= LA.norm(data-data1,2)
print(ed)
print(fraudulentClaims.shape)

(15419, 97)
(7248, 97)
0.0
(923, 97)


In [112]:
#remove the smote generated sample from the test set.
k= 0
index= []

#convert numpy array to pd.DataFrame
X_test= pd.DataFrame(X_test)
y_test= pd.DataFrame(y_test)

for i in range(X_test.shape[0]):
    for j in range(fraudulentClaims.shape[0]):
        data= X_test.loc[i]
        data = pd.Series(data).values
        fraudClaims= fraudulentClaims.loc[j]
        fraudClaims= pd.Series(fraudClaims).values
        euclidean_distance= LA.norm(data-fraudClaims,2)   #calculate the euclidean distance
        
        if (euclidean_distance == 0):
            index.append(i)
            break

In [162]:
print(range(len(newTest)))

range(0, 6570)


In [166]:
#convert numpy array to pd.DataFrame
X_test= pd.DataFrame(X_test)
y_test= pd.DataFrame(y_test)

columnName= list(car_features.columns.values)
labelName= ['FraudFound']
print(len(newTest))
neTest= pd.DataFrame(columns= columnName)
neLabel= pd.DataFrame(columns= labelName)

toTake = list(set(range(len(X_test))) - set(index))
neTest = X_test.copy().iloc[toTake]
newLabel = y_test.copy().iloc[toTake]

k= 0
neTest.head()
newLabel.head()

0


0
0  1
1  1
2  0
3  1
4  1

In [167]:
#with non-linear kernel 
#model object
model = svm.SVC(C=2.0,kernel='rbf')
model.fit(X_train,y_train)

/usr/local/anaconda3/lib/python3.5/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=2.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [170]:
print('SVM classifier after removing the synthetic samples from test:')
predicted = model.predict(neTest)
print(type(predicted),predicted.shape,predicted)
print('Accuracy is ',round(accuracy_score(newLabel,model.predict(neTest)) * 100,2))

cm = confusion_matrix(newLabel,predicted)
print("Confusion Matrix:\n",cm)

TN, FP, FN, TP = cm.ravel()
print("TN:",TN)
print("FP:",FP)
print("FN:",FN)
print("TP:",TP)

print("Accuracy:",(TP+TN)/(TP+FP+FN+TN)*100)
print("Sensitivity:",TP/(TP+FN)*100)
print("Specificity:",TN/(TN+FP)*100)

SVM classifier after removing the synthetic samples from test:
<class 'numpy.ndarray'> (7016,) [0 1 1 ..., 0 1 1]
Accuracy is  79.03
Confusion Matrix:
 [[2264 1359]
 [ 112 3281]]
TN: 2264
FP: 1359
FN: 112
TP: 3281
Accuracy: 79.0336374002
Sensitivity: 96.6990863543
Specificity: 62.4896494618
